"""
PDF export endpoint — generates a branded findings report for a project.
"""

import io
import uuid
from datetime import datetime

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_session, get_tenant_id
from app.core.logging import get_logger
from app.models.clause import ClauseFlag
from app.models.project import Project

router = APIRouter(prefix="/projects/{project_id}/export", tags=["Export"])
logger = get_logger(__name__)


@router.get("/pdf")
async def export_pdf(
    project_id: uuid.UUID,
    tenant_id: str = Depends(get_tenant_id),
    session: AsyncSession = Depends(get_session),
):
    # Load project
    proj_result = await session.execute(
        select(Project).where(
            Project.id == project_id,
            Project.organization_id == uuid.UUID(tenant_id),
        )
    )
    project = proj_result.scalar_one_or_none()
    if not project:
        from app.core.exceptions import not_found
        raise not_found("Project")

    # Load findings
    flags_result = await session.execute(
        select(ClauseFlag).where(
            ClauseFlag.project_id == project_id,
            ClauseFlag.organization_id == uuid.UUID(tenant_id),
        ).order_by(ClauseFlag.severity)
    )
    flags = flags_result.scalars().all()

    pdf_bytes = _generate_pdf(project, flags)

    filename = f"contract_review_{project.name}_{datetime.now().strftime('%Y%m%d')}.pdf"
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


_SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
_SEVERITY_COLOR = {
    "critical": "#c0392b",
    "high": "#e67e22",
    "medium": "#f1c40f",
    "low": "#27ae60",
    "info": "#2980b9",
}


def _generate_pdf(project, flags) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import HRFlowable, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, leftMargin=20*mm, rightMargin=20*mm, topMargin=20*mm, bottomMargin=20*mm)
    styles = getSampleStyleSheet()
    brand = colors.HexColor("#1e3a5f")

    label_style = ParagraphStyle("Label", parent=styles["Normal"], fontSize=7, textColor=colors.grey)
    body_style = ParagraphStyle("Body", parent=styles["Normal"], fontSize=9, leading=13)
    heading3 = ParagraphStyle("H3", parent=styles["Heading3"], textColor=brand, spaceAfter=4)

    story = []

    # ── Cover ─────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 30*mm))
    story.append(Paragraph("Contract Review Report", styles["Title"]))
    story.append(Spacer(1, 6))
    story.append(Paragraph(f"Project: <b>{project.name}</b>", styles["Heading2"]))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%d %B %Y, %H:%M IST')}", styles["Normal"]))
    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", thickness=1, color=brand))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "<i>This report is generated by AI and is intended to assist legal review, "
        "not replace it. All findings must be reviewed by a qualified legal professional "
        "before any contractual decisions are made.</i>",
        ParagraphStyle("Disclaimer", parent=styles["Italic"], fontSize=8, textColor=colors.grey),
    ))

    # ── Executive summary ─────────────────────────────────────────────────────
    story.append(Spacer(1, 10))
    story.append(Paragraph("Executive Summary", styles["Heading2"]))

    severity_counts: dict[str, int] = {}
    for f in flags:
        severity_counts[f.severity] = severity_counts.get(f.severity, 0) + 1

    summary_data = [["Severity", "Count"]]
    for sev in ["critical", "high", "medium", "low", "info"]:
        if sev in severity_counts:
            summary_data.append([sev.capitalize(), str(severity_counts[sev])])
    summary_data.append(["Total", str(len(flags))])

    summary_table = Table(summary_data, colWidths=[100, 60])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), brand),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (1, 0), (1, -1), "CENTER"),
    ]))
    story.append(summary_table)

    # ── Findings index table ──────────────────────────────────────────────────
    if flags:
        story.append(Spacer(1, 10))
        story.append(Paragraph("Findings Index", styles["Heading2"]))
        table_data = [["#", "Severity", "Title", "Type", "Review Status"]]
        for i, flag in enumerate(flags, 1):
            sev_color = colors.HexColor(_SEVERITY_COLOR.get(flag.severity, "#888888"))
            table_data.append([
                str(i),
                Paragraph(f'<font color="{_SEVERITY_COLOR.get(flag.severity, "#888888")}">'
                          f'<b>{flag.severity.upper()}</b></font>', body_style),
                Paragraph(flag.title[:70], body_style),
                (flag.flag_type or "").replace("_", " ").title()[:30],
                (flag.reviewer_status or "pending").capitalize(),
            ])

        index_table = Table(table_data, colWidths=[20, 55, 210, 100, 65])
        index_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), brand),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7f9fc")]),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(index_table)

    # ── Per-finding detail ────────────────────────────────────────────────────
    if flags:
        story.append(PageBreak())
        story.append(Paragraph("Finding Details", styles["Heading2"]))

        for i, flag in enumerate(flags, 1):
            story.append(Spacer(1, 6))
            sev_hex = _SEVERITY_COLOR.get(flag.severity, "#888888")
            story.append(Paragraph(
                f'{i}. <font color="{sev_hex}"><b>[{flag.severity.upper()}]</b></font> {flag.title}',
                styles["Heading3"],
            ))
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#dddddd")))

            meta = [
                ("Type", (flag.flag_type or "").replace("_", " ").title()),
                ("Review Status", (flag.reviewer_status or "pending").capitalize()),
            ]
            if flag.risk_score is not None:
                meta.append(("Risk Score", f"{flag.risk_score}/10"))
            if flag.law_act_name:
                meta.append(("Law Reference", f"{flag.law_act_name}" + (f", §{flag.law_section_number}" if flag.law_section_number else "")))

            meta_table = Table([[k, v] for k, v in meta], colWidths=[80, 370])
            meta_table.setStyle(TableStyle([
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.grey),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ]))
            story.append(meta_table)
            story.append(Spacer(1, 4))

            story.append(Paragraph("Description:", label_style))
            story.append(Paragraph(flag.description or "", body_style))

            if flag.recommendation:
                story.append(Spacer(1, 4))
                story.append(Paragraph("Recommendation:", label_style))
                story.append(Paragraph(flag.recommendation, body_style))

            if flag.reviewer_note:
                story.append(Spacer(1, 4))
                story.append(Paragraph("Reviewer Note:", label_style))
                story.append(Paragraph(flag.reviewer_note, body_style))

    # ── Risk register (critical + high only) ─────────────────────────────────
    high_risk = [f for f in flags if f.severity in ("critical", "high")]
    if high_risk:
        story.append(PageBreak())
        story.append(Paragraph("Risk Register", styles["Heading2"]))
        story.append(Paragraph(
            "The following findings require immediate attention before the contract can be executed.",
            body_style,
        ))
        story.append(Spacer(1, 8))
        risk_data = [["#", "Severity", "Title", "Recommendation"]]
        for i, flag in enumerate(high_risk, 1):
            risk_data.append([
                str(i),
                flag.severity.upper(),
                Paragraph(flag.title[:60], body_style),
                Paragraph((flag.recommendation or "—")[:120], body_style),
            ])
        risk_table = Table(risk_data, colWidths=[20, 55, 170, 205])
        risk_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#c0392b")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#fff5f5")]),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(risk_table)

    doc.build(story)
    return buffer.getvalue()
